# SPDX-FileCopyrightText: 2020 TQ Tezos
# SPDX-License-Identifier: MIT

<<: !include "./hpack/module.yaml"

name:                stablecoin
version:             1.3.0

extra-source-files:
- README.md
- ChangeLog.md
- test/resources/stablecoin.tz
- test/resources/metadata.tz

synopsis:            FA2-based tezos stablecoin smart contract
category:            Blockchain

description:         Please see the README on GitHub at <https://github.com/tqtezos/stablecoin#readme>

verbatim:
  cabal-version: 2.2

library:
  <<: *lib-common

  dependencies:
    - morley-prelude
    - morley-client
    - morley-ledgers
    - lorentz
    - morley
    - containers
    - indigo
    - tasty-quickcheck
    - fmt
    - optparse-applicative
    - file-embed
    - cleveland
    - process
    - megaparsec
    - caps
    - text

executables:
  stablecoin-client:
    main: Main.hs
    source-dirs: client

    dependencies:
      - morley-prelude
      - stablecoin

tests:
  stablecoin-test:
    <<: *test-common
    source-dirs:
      - test
      - test-common

    dependencies:
      - morley
      - morley-prelude
      - morley-ledgers-test
      - lorentz
      - cleveland
      - tasty
      - tasty-hspec
      - tasty-hedgehog
      - hedgehog
      - stablecoin
      - hspec
      - containers
      - mtl
      - fmt

  stablecoin-nettest:
    <<: *test-common
    source-dirs:
      - test-common
      - nettest

    dependencies:
      - containers
      - lorentz
      - morley
      - morley-client
      - cleveland
      - morley-prelude
      - optparse-applicative
      - stablecoin
      - with-utf8
      - fmt
